language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=<1.7
  - DJANGO_VERSION=<1.8
install:
  - pip install -q django$DJANGO_VERSION
  - pip install -q .
  - pip install coveralls
script:
  - coverage run --module unittest discover
  - coverage combine
after_success:
  - coveralls
