language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION="<1.7"
  - DJANGO_VERSION="<1.8"
install:
  - pip install django$DJANGO_VERSION
  - pip install .
  - pip install coveralls
script:
  - PYTHONPATH=. coverage run --module unittest discover
after_success:
  - coverage combine
  - coverage report
  - coveralls
